services:
  - type: web
    name: university-app
    env: node
    buildCommand: npm install && npm run build
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_SITE_URL
        fromService:
          type: web
          name: university-app
          property: url
    plan: starter
    scaling:
      minInstances: 1
      maxInstances: 1
    runtime: node
    websocket: true 