
import Head from 'next/head'
// issues
// There's an issue with the mobile nav ooo, make sure u fix it

export default function Home() {
  return (
    <>
      <Head>
        <title>JCG</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/favicon.ico" />
      </Head>
     

     
      {/* <Faq /> */}
      
    </>
  )
}
